# -*- coding: utf-8 -*-
{
    'name': 'Legal',
    'version': '0.2.0',
    'description': 'Legal',
    'category': 'base.module_category_knowledge_management',
    'author': 'ADHOC',
    'website': 'www.adhoc.com.ar',
    'license': 'AGPL-3',
    'depends': ['calendar', 'portal'],
    'data': [
        'security/legal_group.xml',
        'security/ir.model.access.csv',
        'view/legal_menuitem.xml',
        'view/res_partner_view.xml',
        'view/process_view.xml',
        'view/claims_view.xml',
        'view/radication_view.xml',
        'view/auxiliary_field_view.xml',
        'view/models_view.xml',
        'view/office_view.xml',
        'view/regulation_view.xml',
        'view/events_view.xml',
        'view/parts_view.xml',
        'view/evidence_view.xml',
        'view/negotiation_view.xml',
        'view/claims_type_view.xml',
        'view/responsibility_view.xml',
        'process_data.xml'
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'demo': [
        # 'data/demo/res.partner.csv',
        # 'data/demo/res_users.xml',
        # 'data/demo/res_company.xml',
        # 'data/demo/legal.office.csv',
        # 'data/demo/legal.status.csv',
        # 'data/demo/legal.process_type.csv',
        # 'data/demo/legal.process.csv',
        # 'data/demo/legal.models.csv'
        ],
}
